name: Format

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: cargo fmt -- --check
